### ISSUE TITLE
raspbian-shrink & f2fs

### ISSUE THREAD

**Issue by retrostrobe** [aoakley/cotswoldjam#2]
Hi Andrew, thanks for this super handy script. It makes the whole process of shrinking super simple, so thanks for creating it. This is not an issue, but more a query. To tackle corrupt files on a micro sd card, I've decided to use f2fs to trial it and see whether it helps. I tried to shrink an image with f2fs, but as I found out there is no way of shrinking a f2fs partition. Was mainly wondering if you would have a different approach? For now I've zipped the image file, which seems to compress really well 15GB to 600MB.

**Comment by aoakley** [comment]
I don't have any knowledge of f2fs, but my program does two things:

1. Resizes the partition leaving a minimal amount of free space. This makes
it faster to write copies to other SD cards (because writing 3GB is faster
than writing 16GB).

2. Zero-fills that minimal free space. This makes it compress better.

If all you are concerned about is compression size, then all you need to
worry about is 2.

Resizing (1) is down to the tools and capabilities of the filesystem. I
find it difficult to believe that any modern filesystem can't be resized
somehow (typically only when unmounted) so I would guess that it is just a
case of finding (or writing) the right tool.

Good luck with your project,


-- 
Andrew Oakley andrew@aoakley.com

**Comment by retrostrobe** [comment]
Thanks for the reply. I'll do some more research around the tools available and figure out if I can integrate it with your script.
